# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Password(object):
    def setupUi(self, Password):
        Password.setObjectName("Password")
        Password.resize(597, 266)
        Password.setMinimumSize(QtCore.QSize(597, 266))
        Password.setMaximumSize(QtCore.QSize(597, 266))
        self.centralwidget = QtWidgets.QWidget(Password)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 140, 321, 111))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                        "    font-size: 40px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: green;\n"
                                        "}")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 571, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 221, 111))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.checkBox.setStyleSheet("")
        self.checkBox.setIconSize(QtCore.QSize(16, 16))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setChecked(True)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(130, 20, 70, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(130, 50, 71, 22))
        self.spinBox.setMinimum(6)
        self.spinBox.setMaximum(30)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 80, 111, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        Password.setCentralWidget(self.centralwidget)

        self.retranslateUi(Password)
        QtCore.QMetaObject.connectSlotsByName(Password)

    def retranslateUi(self, Password):
        _translate = QtCore.QCoreApplication.translate
        Password.setWindowTitle(_translate("Password", "MainWindow"))
        self.pushButton.setText(_translate("Password", "Пароль"))
        self.plainTextEdit.setPlaceholderText(_translate("Password", "1234567890..."))
        self.groupBox.setTitle(_translate("Password", "Режим "))
        self.checkBox.setText(_translate("Password", "Цифры"))
        self.checkBox_2.setText(_translate("Password", "Буквы строчные"))
        self.checkBox_3.setText(_translate("Password", "Символы"))
        self.checkBox_4.setText(_translate("Password", "Буквы заглавные"))
